name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: checkout code
      uses: deep5050/cppcheck-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN}}
